Adds id key to issue for validation
renatahodovan/fuzzinator pull request #30
Opened 2020-11-30 14:58 UTC by pmatos

Fixes #29

2020-11-30 14:59 UTC, pmatos commented
Unsure I understood the code enough for this to make sense, but it seems that the error is now gone as I moved the `add_issue` call, which adds the `id` key to `issue` before the `if`.

2020-11-30 22:26 UTC, renatahodovan requested changes
The issue is well spotted, but the fix is not exactly right. I suggest to touch `CallJob.add_issue` first, move the ID generation snippet (call_job.py:36-40) from there into a new utility method (e.g., `CallJob.ensure_id`) and use this method both in `CallJob.add_issue` and in `ValidateJob.validate` (validate_job.py: inbetween lines 42-43) to set a default value for the `id` field if it doesn't exist.

2020-12-01 11:00 UTC, pmatos commented
@renatahodovan thanks for the review and comments. Pushed a new version.

2020-12-01 11:13 UTC, renatahodovan requested changes

2020-12-01 11:13 UTC, renatahodovan commented on fuzzinator/job/call_job.py
> +        assert 'test' in issue
This assert is not needed.

2020-12-01 11:13 UTC, renatahodovan commented on fuzzinator/job/call_job.py
> +        test = issue['test']
The declaration of `test` variable should go inside the next if statement.

2020-12-01 11:13 UTC, renatahodovan commented on fuzzinator/job/reduce_job.py
> +        print("Running job reduction - calling ValidateJob\n")
Leftover debug print. Please remove.

2020-12-01 11:13 UTC, renatahodovan commented on fuzzinator/job/validate_job.py
> +            assert 'id' in self.issue
These asserts are not needed either, since `ensure_id` enforces to have an `id` field in issue.

2020-12-01 11:13 UTC, renatahodovan commented on fuzzinator/job/validate_job.py
> +
Unnecessary spaces, please remove.

2020-12-01 12:58 UTC, pmatos commented
Thanks for your comments on this.

2020-12-01 23:48 UTC, renatahodovan approved these changes
LGTM.

2020-12-02 00:01 UTC, akosthekiss requested changes
The lint job on Travis CI reports errors. (No idea why this is not shown at the PR.)

```
************* Module fuzzinator.job.call_job
247fuzzinator/job/call_job.py:38: [C0303(trailing-whitespace), ] Trailing whitespace
248fuzzinator/job/call_job.py:53: [C0305(trailing-newlines), ] Trailing newlines
```

Could you please fix these. You can check things locally by running `tox` (to perform all checks) or `tox -e lint` (to do the linting only).

Sorry for the late hit.

2020-12-02 10:24 UTC, pmatos commented
> The lint job on Travis CI reports errors. (No idea why this is not shown at the PR.)
> 
> ```
> ************* Module fuzzinator.job.call_job
> 247fuzzinator/job/call_job.py:38: [C0303(trailing-whitespace), ] Trailing whitespace
> 248fuzzinator/job/call_job.py:53: [C0305(trailing-newlines), ] Trailing newlines
> ```
> 
> Could you please fix these. You can check things locally by running `tox` (to perform all checks) or `tox -e lint` (to do the linting only).
> 
> Sorry for the late hit.

Thanks for pointing that out to me. I hadn't noticed there were some tests we could run. :)

2020-12-02 10:43 UTC, pmatos commented
Tox is now happy on my side:
```
______________________________________________ summary ______________________________________________
  py: commands succeeded
  lint: commands succeeded
  eslint: commands succeeded
  docs: commands succeeded
  congratulations :)
```

Feel free to merge if you're happy as well. :)

2020-12-02 13:44 UTC, akosthekiss approved these changes
LGTM

2020-12-02 14:06 UTC, pmatos commented
> LGTM

I can't merge - can you please do it?

2020-12-02 16:01 UTC, merged